# Based off of https://nextjs.org/docs/deployment#docker-image
# Install dependencies for all subprojects
FROM node:alpine AS base
WORKDIR /app
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
# Install lerna
RUN yarn global add lerna
# Root package.json for all modules
COPY package.json yarn.lock ./
# Install dependencies
RUN yarn install --frozen-lockfile
# Copy files from ui and common
COPY packages/common ./packages/common
COPY packages/ui ./packages/ui
# Install all subpackages' node_modules with lerna
COPY lerna.json tsconfig.json ./
RUN yarn run bootstrap


# Install UI dependencies
FROM node:alpine AS ui-builder
RUN apk add --no-cache libc6-compat
WORKDIR /app/packages/ui
# Copy from common and ui and build ui project
COPY --from=base /app/packages/common /app/packages/common
COPY --from=base /app/packages/ui .
# Envs are required at build time
ARG NEXT_PUBLIC_API_URL=http://0.0.0.0:3000/graphql
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN yarn build && yarn install --production --ignore-scripts --prefer-offline


# Production image, copy all the files and run next
FROM node:alpine AS runner
WORKDIR /app/packages/ui
ENV NODE_ENV production
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
# Copy only necessary files
COPY --from=ui-builder /app/packages/ui/.env ./.env
COPY --from=ui-builder /app/packages/ui/next.config.js ./
COPY --from=ui-builder /app/packages/ui/public ./public
COPY --from=ui-builder --chown=nextjs:nodejs /app/packages/ui/.next ./.next
COPY --from=ui-builder /app/packages/ui/node_modules ./node_modules
COPY --from=ui-builder /app/packages/ui/package.json ./package.json
USER nextjs
ARG PORT=8000
EXPOSE $PORT
# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT $PORT
CMD ["yarn", "start"]
